# Generated by Django 5.2.13 on 2026-08-17 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Global Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='merchantprofile',
            options={'verbose_name_plural': 'Merchant Profiles'},
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='additional_direction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='app_update_notification_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='building_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='floor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='general_notification_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='nearby_landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='payment_notification_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='shop_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='offers', to='merchant.menuitem'),
        ),
        migrations.AlterField(
            model_name='category',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='merchant.merchantprofile'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='preparation_time_min',
            field=models.PositiveIntegerField(blank=True, default=15, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='merchants', to='merchant.globalcategory'),
        ),
        migrations.CreateModel(
            name='MerchantVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=255)),
                ('cac_registration_no', models.CharField(max_length=100)),
                ('cac_document', models.URLField()),
                ('account_no', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='merchant.merchantprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Merchant Verifications',
            },
        ),
        migrations.CreateModel(
            name='MerchantSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_open', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='merchant.merchantprofile')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('merchant', 'day_of_week')},
            },
        ),
    ]
