# Generated by Django 5.2.13 on 2026-08-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_itemreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='language',
            field=models.CharField(choices=[('en_us', 'English (US)'), ('en_uk', 'English (UK)'), ('zh', 'Mandarin'), ('hi', 'Hindi'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic'), ('bn', 'Bengali'), ('ru', 'Russian'), ('id', 'Indonesian')], default='en', max_length=10),
        ),
    ]
