# Generated by Django 5.2.13 on 2026-08-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_alter_merchantprofile_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addon',
            options={'ordering': ['size', 'name']},
        ),
        migrations.AlterModelOptions(
            name='addongroup',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='addon',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='addon',
            name='size',
            field=models.CharField(blank=True, choices=[('', 'No Size'), ('regular', 'Regular'), ('large', 'Large'), ('xl', 'XL')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='addongroup',
            name='max_selectable',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = unlimited, 1 = single choice, 2+ = limited'),
        ),
    ]
