from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import (CustomerProfileView, SavedAddressViewSet,
                    PaymentMethodViewSet, ReferralMyView,
                    ReferralInviteView, ReferralApplyView,
                    WalletView, HomeView, HomeListingView,
                    FavoriteToggleView, HomeItemDetailView,
                    RestaurantListView,
                    RestaurantDetailView, MenuItemDetailView, SearchView,
                    CartView, CartAddItemView, CartUpdateItemView,
                    CartRemoveItemView, CartClearView, CheckoutView,
                    MyOrdersView, OrderDetailView, CancelOrderView,
                    TrackOrderView, ReviewCreateView,
                    PaystackInitializeView, PaystackVerifyView,
                    ItemReviewCreateView, ItemReviewsListView,
                    RecentSearchListView, RecentSearchSaveView,
                    RecentSearchDeleteView)

router = DefaultRouter()
router.register('addresses', SavedAddressViewSet,
                basename='addresses')
router.register('payment-methods', PaymentMethodViewSet,
                basename='payment-methods')

urlpatterns = [
    path('profile/', CustomerProfileView.as_view(),
         name='customer-profile'),
    path('wallet/', WalletView.as_view(), name='customer-wallet'),
    path('referrals/', ReferralMyView.as_view(),
         name='customer-referrals'),
    path('referrals/invite/', ReferralInviteView.as_view(),
         name='customer-referral-invite'),
    path('referrals/apply/', ReferralApplyView.as_view(),
         name='customer-referral-apply'),

    path('home/', HomeView.as_view(), name='home'),
    path('home/listing/', HomeListingView.as_view(),
         name='home-listing'),
    path('home/item/<int:pk>/', HomeItemDetailView.as_view(),
         name='home-item-detail'),
    path('favorite/', FavoriteToggleView.as_view(),
         name='favorite-toggle'),

    path('restaurants/', RestaurantListView.as_view(),
         name='restaurants'),
    path('restaurants/<int:pk>/', RestaurantDetailView.as_view(),
         name='restaurant-detail'),
    path('items/<int:pk>/', MenuItemDetailView.as_view(),
         name='item-detail'),
    path('search/', SearchView.as_view(), name='search'),

    path('recent-searches/', RecentSearchListView.as_view(),
         name='recent-searches-list'),
    path('recent-searches/save/', RecentSearchSaveView.as_view(),
         name='recent-searches-save'),
    path('recent-searches/<int:pk>/delete/',
         RecentSearchDeleteView.as_view(),
         name='recent-searches-delete'),
    path('recent-searches/clear/',
         RecentSearchDeleteView.as_view(),
         name='recent-searches-clear'),

    path('cart/', CartView.as_view(), name='cart'),
    path('cart/add/', CartAddItemView.as_view(), name='cart-add'),
    path('cart/update/<int:pk>/', CartUpdateItemView.as_view(),
         name='cart-update'),
    path('cart/remove/<int:pk>/', CartRemoveItemView.as_view(),
         name='cart-remove'),
    path('cart/clear/', CartClearView.as_view(), name='cart-clear'),

    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('orders/', MyOrdersView.as_view(), name='my-orders'),
    path('orders/<int:pk>/', OrderDetailView.as_view(),
         name='order-detail'),
    path('orders/<int:pk>/cancel/', CancelOrderView.as_view(),
         name='cancel-order'),
    path('orders/<int:pk>/track/', TrackOrderView.as_view(),
         name='track-order'),

    path('review/', ReviewCreateView.as_view(),
         name='create-review'),
    path('items/<int:pk>/review/', ItemReviewCreateView.as_view(),
         name='item-review-create'),
    path('items/<int:pk>/reviews/', ItemReviewsListView.as_view(),
         name='item-reviews-list'),

    path('payment/initialize/', PaystackInitializeView.as_view(),
         name='paystack-init'),
    path('payment/verify/', PaystackVerifyView.as_view(),
         name='paystack-verify'),
] + router.urls
