# Generated by Django 5.2.13 on 2026-08-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Extra data: order_id, promo_code, merchant_name, etc.'),
        ),
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_preparing', 'Order Preparing'), ('order_out_for_delivery', 'Out for Delivery'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('rate_order', 'Rate Your Order'), ('promotion', 'Promotion'), ('deal', 'Deal'), ('payment', 'Payment'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
