# Generated by Django 5.2.7 on 2025-10-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0010_dashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
